FROM ubuntu:18.04
RUN sudo apt-get install python3.9
WORKDIR /app
COPY ./src .
RUN pip install virtualenv
RUN python3.9 -m venv py_39
RUN source py_39/bin/activate
RUN pip install -r requirements.txt
